Repository ethereumclassic/explorer, pull requests merged in 2018-11, with the labels that each got.

#184 Test
  .travis.yml
  app/app.js
  package.json
  test/index.js
  test/units/apps.js
  test/units/template.js
Labels: enhancement, waiting for review

#166 cleanup config loading method
  app.js
  config.example.json
  config.json
  routes/stats.js
  routes/web3relay.js
  tools/blockHelper.js
  tools/patcher.js
  tools/stats.js
  tools/sync.js
  tools/tokens/daoTxns.js
Labels: code cleanup

#165 support Rich List
  db.js
  lib/trace.js
  public/js/controllers/AccountsController.js
  public/js/main.js
  public/tpl/header.html
  public/views/accounts.html
  routes/index.js
  routes/richlist.js
  routes/web3relay.js
  tools/richlist.js
  tools/sync.js
Labels: enhancement, review in progress
